# Generated by Django 2.0.1 on 2018-03-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
