# Generated by Django 2.0.1 on 2018-03-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180322_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
