# Generated by Django 2.0.1 on 2018-04-08 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180325_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=24, null=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'verbose_name': 'currency',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateField(verbose_name='on date')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_currency', to='product.Currency')),
                ('quoted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoted_currency', to='product.Currency')),
            ],
            options={
                'verbose_name_plural': 'quotations',
                'verbose_name': 'quotation',
            },
        ),
        migrations.CreateModel(
            name='Product_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name_plural': 'current prices',
                'verbose_name': 'current price',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product_price',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product'),
        ),
    ]
