# Generated by Django 2.0.1 on 2018-04-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20180408_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
