# Generated by Django 2.0.1 on 2018-04-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20180409_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='_price',
        ),
    ]
