# Generated by Django 2.0.1 on 2018-04-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_product_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_in_cart',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
