# Generated by Django 2.0.1 on 2018-04-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product__price'),
        ('order', '0006_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_in_cart',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Currency'),
        ),
        migrations.AddField(
            model_name='product_in_order',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Currency'),
        ),
    ]
